### ISSUE TITLE
remove windows xp related tweak to suppress new hardware dialog

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo#166]
The windows xp related tweak to remove new hardware dialog after sync is not needed anymore. Should be removed.

**Comment by sharky009** [comment]
Hi Thomas,
I would like to keep this tweaks as long as they dont disturb in any way. For some purposes people still use xp machines (without net access). I am one of this because some old software didnt work on newer Version of Windows. But thats only my opinion. Im interested to hear what other people think.

Greetings
Pascal

**Comment by HappyBasher** [comment]
Done in linuxmuster-linbo7.
